server:
  port: 81
user:
  uname: zhangsan
  pwd: 123

##############  log  ################
logging:
	path=E://log
	level:
		org:
			springframework:
				web:INFO
			hibernate:ERROR
		com:example:demo:controller:DEBUG
		
	
mybatis:
	type-aliases-package:com.example.demo.entity
	mapper-locations:classpath:mappers/*.xml

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
	
#############数据库连接#############
spring:
	mvc:
		view:
			prefix:/WEB-INF/jsp/
			suffix:.jsp
	application:
		name:kooker
	datasource:
		url:jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
		username:root
		password:1234
		driver-class-name:com.mysql.cj.jdbc.Driver
	