server:
 port: 8189
user:
 uname: zhangsan
 pwd: 123

##############  log  ################
logging:
 path: E://log
 level:
  org:
   springframework:
   web: INFO
   hibernate: ERROR
  com:example: demo:controller:DEBUG
		
	
mybatis:
 type-aliases-package: com.example.demo.entity
 mapper-locations: classpath:mappers/*.xml


	
#############数据库连接#############
spring: 
 mvc: 
 view: 
  prefix: /WEB-INF/jsp/
  suffix: .jsp
 application: 
  name: kooker
 datasource:
  url: jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  username: root
  password: 1234
  driver-class-name: com.mysql.cj.jdbc.Driver
####配置redis数据库###
 redis: 
  database: 1
  host: 192.168.13.130
  port: 6379
  password: 111111
  lettuce: 
   pool: 
    max-wait: -1
    max-idle: 8
    min-idle: 0
		
		
		
		
		
		
	