








logging: # log
 path: E://log
 level:
  com: 
   example: 
    demo: 
     controller: DEBUG
  org:
   springframework:
    web: INFO
   hibernate: ERROR
  
		
	
mybatis:
 type-aliases-package: com.example.demo.entity
 mapper-locations: classpath:mappers/*.xml

	
spring: 
 mvc: 
  view: 
   prefix: /WEB-INF/jsp/
   suffix: .jsp

 datasource:  # 数据库连接
  url: jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  username: root
  password: 1234
  driver-class-name: com.mysql.cj.jdbc.Driver

server:
 port: '8189'

