package com.example.demo.entity;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.name
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.desc_name
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    private String descName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.url
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.name
     *
     * @return the value of permission.name
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.name
     *
     * @param name the value for permission.name
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.desc_name
     *
     * @return the value of permission.desc_name
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    public String getDescName() {
        return descName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.desc_name
     *
     * @param descName the value for permission.desc_name
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    public void setDescName(String descName) {
        this.descName = descName == null ? null : descName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.url
     *
     * @return the value of permission.url
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.url
     *
     * @param url the value for permission.url
     *
     * @mbg.generated Wed Aug 21 15:40:47 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}