package com.example.demo.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usid
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    private Integer usid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upwd
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    private String upwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.state
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usid
     *
     * @return the value of user.usid
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    public Integer getUsid() {
        return usid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usid
     *
     * @param usid the value for user.usid
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    public void setUsid(Integer usid) {
        this.usid = usid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upwd
     *
     * @return the value of user.upwd
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upwd
     *
     * @param upwd the value for user.upwd
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.state
     *
     * @return the value of user.state
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.state
     *
     * @param state the value for user.state
     *
     * @mbg.generated Wed Aug 21 14:47:25 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }
}